### ISSUE TITLE
请问USB插件怎么起作用？

### ISSUE THREAD

**Issue by nijisakai** [wangshub/hammerspoon-config#13]
插上USB没有看到有什么提示
谢谢开发者

**Comment by wangshub** [comment]
@nijisakai 只是写了一个示例，有 USB 设备时，有如下 Log

![image](https://user-images.githubusercontent.com/20924010/57193598-520ac000-6f6f-11e9-9242-3e4734c8359e.png)

**Comment by nijisakai** [comment]
谢谢~
