### ISSUE TITLE
weather 怎么自动更新

### ISSUE THREAD

**Issue by longgediyi999** [wangshub/hammerspoon-config#2]
早上9点左右打开电脑还是昨天的9号在最前面       还有需要一个  yin = '☁️'

**Comment by wangshub** [comment]
@longgediyi999 https://github.com/wangshub/hammerspoon-config/blob/master/weather/weather.lua#L52

每 1 个小时会更新一次

**Comment by longgediyi999** [comment]
早上9点开机一直到现在 也没更新 需要手动reload config一下  是我哪里配置有问题吗    
------------------ 原始邮件 ------------------
发件人: "神奇的战士"<notifications@github.com>;
发送时间: 2019年4月10日(星期三) 中午11:16
收件人: "wangshub/hammerspoon-config"<hammerspoon-config@noreply.github.com>;
抄送: "潇凌"<1042879661@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [wangshub/hammerspoon-config] weather 怎么自动更新 (#2)




Closed #2.

**Comment by wangshub** [comment]
@longgediyi999 能否麻烦改一下这个定时器时间，例如改成 10s ，然后看下hammerspoon 的 Console 在自动更新的时候有没有报错呢？

**Comment by wangshub** [comment]
https://github.com/wangshub/hammerspoon-config/blob/master/weather/weather.lua#L54

**Comment by longgediyi999** [comment]
没有报错哈  现在已经reload了 变成11号了 


------------------ 原始邮件 ------------------
发件人: "神奇的战士"<notifications@github.com>;
发送时间: 2019年4月11日(星期四) 上午10:49
收件人: "wangshub/hammerspoon-config"<hammerspoon-config@noreply.github.com>;
抄送: "潇凌"<1042879661@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [wangshub/hammerspoon-config] weather 怎么自动更新 (#2)




https://github.com/wangshub/hammerspoon-config/blob/master/weather/weather.lua#L54

**Comment by wangshub** [comment]
@longgediyi999 是我的原因，应该用 doEvery, 已经改过来了 https://github.com/wangshub/hammerspoon-config/blob/master/weather/weather.lua#L54

**Comment by longgediyi999** [comment]
OK




------------------ 原始邮件 ------------------
发件人: "神奇的战士"<notifications@github.com>;
发送时间: 2019年4月12日(星期五) 上午9:40
收件人: "wangshub/hammerspoon-config"<hammerspoon-config@noreply.github.com>;
抄送: "潇凌"<1042879661@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [wangshub/hammerspoon-config] weather 怎么自动更新 (#2)




@longgediyi999 是我的原因，应该用 doEvery, 已经改过来了 https://github.com/wangshub/hammerspoon-config/blob/master/weather/weather.lua#L54
