### ISSUE TITLE
ime.lua:29: attempt to index a nil value

### ISSUE THREAD

**Issue by BH1SCW** [wangshub/hammerspoon-config#9]
2019-04-16 15:07:48: 15:07:48 ERROR:   LuaSkin: hs.application.watcher callback: /Users/kong/.hammerspoon/ime/ime.lua:29: attempt to index a nil value
stack traceback:
	/Users/kong/.hammerspoon/ime/ime.lua:29: in function 'updateFocusAppInputMethod'
	/Users/kong/.hammerspoon/ime/ime.lua:62: in function 'applicationWatcher'
2019-04-16 15:07:48: ********

**Comment by BH1SCW** [comment]
System Preferences > Security & Privacy > Privacy tab > Accessibility

and then check the box to allow Hammerspoon to control your computer

**Comment by 1206lyp** [comment]
same issue

**Comment by wangshub** [comment]
should be fixed by commit https://github.com/wangshub/hammerspoon-config/commit/36f0a6439976f7301809b577376fbbc84006ad77 , could you try again? @BH1SCW @1206lyp
